steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/agesis:$BUILD_ID',
    '--build-arg', 'VITE_GOOGLE_MAPS_API_KEY=$_VITE_GOOGLE_MAPS_API_KEY',
    '--build-arg', 'VITE_API_URL=$_VITE_API_URL',
    '--build-arg', 'VITE_SOCKET_URL=$_VITE_SOCKET_URL',
    '.'
  ]
# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/agesis:$BUILD_ID']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 'deploy', 'agesis',
    '--image', 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/agesis:$BUILD_ID',
    '--region', 'asia-south1',
    '--platform', 'managed',
    '--allow-unauthenticated',
    '--update-env-vars', 'NODE_ENV=production'
  ]
images:
- 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/agesis:$BUILD_ID'
substitutions:
  _VITE_GOOGLE_MAPS_API_KEY: 'AIzaSyC697sSZTaafmJj7nFAW_yvrJTNsWsRfNk'
  _VITE_API_URL: '/api'
  _VITE_SOCKET_URL: '/'
