import { useState } from 'react';
import { motion } from 'framer-motion';
import { reportAPI } from '../../services/api';
import PageWrapper from '../../components/layout/PageWrapper';
import { FileText, Download, Loader2, Calendar, Check } from 'lucide-react';
import jsPDF from 'jspdf';

export default function LegalReport() {
  const [options, setOptions] = useState({ includeAnalyses: true, includeEvidence: true, includeAlerts: true });
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(false);

  const generate = async () => {
    setLoading(true);
    try { const { data } = await reportAPI.generate(options); setReport(data.report); }
    catch { setReport({ generatedAt: new Date().toISOString(), user: { name: 'User' }, summary: { totalAnalyses: 0, totalEvidence: 0, totalAlerts: 0, averageRiskScore: 0 }, timeline: [] }); }
    setLoading(false);
  };

  const downloadPDF = () => {
    if (!report) return;
    const doc = new jsPDF();
    doc.setFontSize(20); doc.text('AEGESIS Legal Report', 20, 25);
    doc.setFontSize(10); doc.text(`Generated: ${new Date(report.generatedAt).toLocaleString('en-IN')}`, 20, 35);
    doc.text(`User: ${report.user?.name || 'N/A'}`, 20, 42);
    doc.setFontSize(14); doc.text('Summary', 20, 55);
    doc.setFontSize(10);
    doc.text(`Total Analyses: ${report.summary.totalAnalyses}`, 25, 65);
    doc.text(`Total Evidence: ${report.summary.totalEvidence}`, 25, 72);
    doc.text(`Total Alerts: ${report.summary.totalAlerts}`, 25, 79);
    doc.text(`Average Risk Score: ${report.summary.averageRiskScore}/100`, 25, 86);
    let y = 100;
    if (report.timeline?.length > 0) {
      doc.setFontSize(14); doc.text('Timeline', 20, y); y += 10;
      doc.setFontSize(9);
      report.timeline.slice(0, 20).forEach(item => {
        if (y > 270) { doc.addPage(); y = 20; }
        doc.text(`[${item.type.toUpperCase()}] ${new Date(item.date).toLocaleString('en-IN')}`, 25, y);
        y += 7;
      });
    }
    doc.setFontSize(8); doc.text('This report was generated by AEGESIS Safety Platform', 20, 285);
    doc.save(`aegesis-legal-report-${Date.now()}.pdf`);
  };

  return (
    <PageWrapper title="Legal Report Generator" subtitle="Generate a comprehensive PDF report with timeline, severity analysis, and evidence summary">
      <div className="max-w-3xl mx-auto space-y-6">
        <div className="glass-card p-6">
          <h2 className="text-lg font-semibold text-white mb-4 flex items-center gap-2"><FileText size={20} className="text-amber-400" /> Report Options</h2>
          <div className="space-y-3 mb-6">
            {[
              { key: 'includeAnalyses', label: 'Include AI Analyses' },
              { key: 'includeEvidence', label: 'Include Evidence Items' },
              { key: 'includeAlerts', label: 'Include Alert History' },
            ].map(({ key, label }) => (
              <label key={key} className="flex items-center gap-3 p-3 rounded-xl bg-surface-800/50 cursor-pointer hover:bg-surface-800 transition-all">
                <input type="checkbox" checked={options[key]} onChange={e => setOptions({ ...options, [key]: e.target.checked })} className="sr-only" />
                <div className={`w-5 h-5 rounded-md border-2 flex items-center justify-center transition-all ${options[key] ? 'bg-primary-500 border-primary-500' : 'border-surface-600'}`}>
                  {options[key] && <Check size={12} className="text-white" />}
                </div>
                <span className="text-surface-200 text-sm">{label}</span>
              </label>
            ))}
          </div>
          <button onClick={generate} disabled={loading} className="btn-primary w-full flex items-center justify-center gap-2">
            {loading ? <><Loader2 size={16} className="animate-spin" /> Generating...</> : <><FileText size={16} /> Generate Report</>}
          </button>
        </div>

        {report && (
          <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="glass-card p-6 space-y-4">
            <div className="flex items-center justify-between mb-2">
              <h2 className="text-lg font-semibold text-white">Report Preview</h2>
              <button onClick={downloadPDF} className="btn-primary text-sm flex items-center gap-2"><Download size={14} /> Download PDF</button>
            </div>
            <div className="p-4 rounded-xl bg-surface-800/50 text-xs text-surface-400">
              <p>Generated: {new Date(report.generatedAt).toLocaleString('en-IN')}</p>
              <p>User: {report.user?.name}</p>
            </div>
            <div className="grid grid-cols-3 gap-3">
              <div className="p-3 rounded-lg bg-surface-800/50 text-center"><p className="text-2xl font-bold text-white">{report.summary.totalAnalyses}</p><p className="text-xs text-surface-400">Analyses</p></div>
              <div className="p-3 rounded-lg bg-surface-800/50 text-center"><p className="text-2xl font-bold text-white">{report.summary.totalEvidence}</p><p className="text-xs text-surface-400">Evidence</p></div>
              <div className="p-3 rounded-lg bg-surface-800/50 text-center"><p className="text-2xl font-bold text-white">{report.summary.totalAlerts}</p><p className="text-xs text-surface-400">Alerts</p></div>
            </div>
            {report.timeline?.length > 0 && (
              <div><h3 className="text-white text-sm font-semibold mb-2">Timeline ({report.timeline.length} events)</h3>
                <div className="space-y-2 max-h-48 overflow-y-auto no-scrollbar">
                  {report.timeline.map((item, i) => (
                    <div key={i} className="flex items-center gap-3 p-2 rounded-lg bg-surface-800/30 text-xs">
                      <span className={`badge text-xs ${item.type === 'alert' ? 'badge-danger' : item.type === 'analysis' ? 'badge-warning' : 'badge-primary'}`}>{item.type}</span>
                      <span className="text-surface-400">{new Date(item.date).toLocaleString('en-IN')}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </motion.div>
        )}
      </div>
    </PageWrapper>
  );
}
